DROP TABLE IF EXISTS disputes;
DROP TABLE IF EXISTS transfers;
DROP TABLE IF EXISTS lookups;
DROP TABLE IF EXISTS pets;
DROP TABLE IF EXISTS chips;
DROP TABLE IF EXISTS magic_links;
DROP TABLE IF EXISTS owners;
